package com.shevapro.website.utils

import com.shevapro.website.models.Article

/**
 * IMPORTANT: Automated Markdown Article System
 * 
 * The build system automatically processes markdown files from:
 * - src/jsMain/resources/public/markdown/blog/
 * - src/jsMain/resources/public/markdown/portfolio/
 * 
 * It generates this file (MarkdownArticles.kt) with article metadata during the build process.
 * 
 * Current Implementation:
 * - This file is automatically generated during the build process
 * - It contains a list of all articles found in the markdown directories
 * - The functions getBlogArticles() and getPortfolioArticles() filter this list
 * - This approach ensures that the code compiles and works correctly
 * 
 * To add a new article:
 * 1. Add a new markdown file to the appropriate directory
 * 2. Build the project to regenerate this file with the updated article list
 * 
 * The system is now fully automated - no need to manually update article lists!
 */
data class ArticleDescriptor(
    val route: String,
    val filePath: String,
    val title: String?,
    val description: String?,
    val date: String?,
    val tags: List<String>,
    val thumbnail: String?
)

// Auto-generated list of articles from markdown files
private val markdownIndex = listOf(
    ArticleDescriptor(
    route = "/blog/new-test-article",
    filePath = "/markdown/blog/new_test_article.md",
    title = "New Test Article",
    description = "This is a test article to verify that the automation system correctly picks up new markdown files and includes them in the website.",
    date = "January 28, 2025",
    tags = listOf("test", "automation", "blog", "new"),
    thumbnail = null
),
    ArticleDescriptor(
    route = "/blog/welcome-to-my-blog",
    filePath = "/markdown/blog/welcome_to_my_blog.md",
    title = "Welcome to My Blog",
    description = "An introduction to my blog and what you can expect to find here. I'll be sharing insights about software development, technology trends, and my personal journey.",
    date = "January 15, 2024",
    tags = listOf("personal", "introduction", "blog"),
    thumbnail = null
),
    ArticleDescriptor(
    route = "/blog/kotlin-multiplatform-guide",
    filePath = "/markdown/blog/kotlin_multiplatform_guide.md",
    title = "Getting Started with Kotlin Multiplatform",
    description = "Learn how to set up and build your first Kotlin Multiplatform project. This guide covers the basics and best practices for sharing code between Android, iOS, and web platforms.",
    date = "February 2, 2024",
    tags = listOf("kotlin", "multiplatform", "mobile", "tutorial"),
    thumbnail = null
),
    ArticleDescriptor(
    route = "/portfolio/example",
    filePath = "/markdown/portfolio/example.md",
    title = "Example",
    description = "Testing Table, strikethrough and more.Testing Table, strikethrough and more. Testing Table, strikethrough and more.Testing Table, strikethrough and more",
    date = "June 1, 2020",
    tags = listOf("md", "test", "kotlin"),
    thumbnail = "blank-image.jpeg"
),
    ArticleDescriptor(
    route = "/portfolio/markdown-example",
    filePath = "/markdown/portfolio/markdown_example.md",
    title = "Markdown Example",
    description = "A comprehensive example showcasing various markdown formatting features and capabilities.",
    date = "December 1, 2023",
    tags = listOf("markdown", "example", "formatting", "demo"),
    thumbnail = "blank-image.jpeg"
),
    ArticleDescriptor(
    route = "/portfolio/unified-test",
    filePath = "/markdown/portfolio/unified_test.md",
    title = "Unified Markdown Processing Test",
    description = "Testing unified markdown processing with remark-gfm and rehype-raw plugins",
    date = "January 28, 2025",
    tags = listOf("unified", "remark", "rehype", "gfm", "test"),
    thumbnail = "blank-image.jpeg"
),
    ArticleDescriptor(
    route = "/portfolio/file-sorter-app",
    filePath = "/markdown/portfolio/file_sorter_app.md",
    title = "File Sorter",
    description = "Your ultimate solution for keeping your digital life neat and tidy! With File Sorter, you can easily organize your files on your Android device by moving them from one folder to another based on their extensions. No more cluttered folders and lost files!",
    date = "September 8, 2023",
    tags = listOf("android", "app", "hobby", "productivity"),
    thumbnail = "file-sorter-logo.png"
),
    ArticleDescriptor(
    route = "/portfolio/enhanced-test",
    filePath = "/markdown/portfolio/enhanced_test.md",
    title = "Enhanced Markdown Test",
    description = "Testing enhanced markdown processing with unified, remark-gfm, and rehype-raw",
    date = "July 28, 2025",
    tags = listOf("test"),
    thumbnail = "blank-image.jpeg"
)
)

fun ArticleDescriptor.toArticle(): Article {
    val slug = route.substringAfterLast("/")
    val isPortfolioArticle = route.startsWith("/portfolio")

    return Article(
        id = slug,
        slug = slug,
        title = title ?: "Untitled",
        content = "", // Content will be loaded separately when needed
        description = description ?: "",
        author = "Shevapro",
        dateAdded = date ?: "",
        tags = tags,
        imageUrl = if (thumbnail != null) "/assets/images/$thumbnail" else "/favicon.ico",
        isPortfolioArticle = isPortfolioArticle,
        posted = true
    )
}

/**
 * Returns a list of blog articles.
 * 
 * This function filters the auto-generated markdownIndex list for articles with routes
 * that start with "/blog" and converts them to Article objects.
 * 
 * The list is automatically updated when new markdown files are added to the blog directory.
 */
fun getBlogArticles(): List<Article> {
    // Use the auto-generated markdownIndex list to get blog articles
    return markdownIndex
        .filter { it.route.startsWith("/blog") }
        .map { it.toArticle() }
}

/**
 * Returns a list of portfolio articles.
 * 
 * This function filters the auto-generated markdownIndex list for articles with routes
 * that start with "/portfolio" and converts them to Article objects.
 * 
 * The list is automatically updated when new markdown files are added to the portfolio directory.
 */
fun getPortfolioArticles(): List<Article> {
    // Use the auto-generated markdownIndex list to get portfolio articles
    return markdownIndex
        .filter { it.route.startsWith("/portfolio") }
        .map { it.toArticle() }
}