package com.shevapro.website.utils

import com.shevapro.website.models.Article

/**
 * IMPORTANT: Automated Markdown Article System
 * 
 * The build system automatically processes markdown files from:
 * - src/jsMain/resources/public/content/blog/
 * - src/jsMain/resources/public/content/portfolio/
 * 
 * It generates this file (MarkdownArticles.kt) with article metadata during the build process.
 * 
 * Current Implementation:
 * - This file is automatically generated during the build process
 * - It contains a list of all articles found in the markdown directories
 * - The functions getBlogArticles() and getPortfolioArticles() filter this list
 * - This approach ensures that the code compiles and works correctly
 * 
 * To add a new article:
 * 1. Add a new markdown file to the appropriate directory
 * 2. Build the project to regenerate this file with the updated article list
 * 
 * The system is now fully automated - no need to manually update article lists!
 */
data class ArticleDescriptor(
    val route: String,
    val filePath: String,
    val title: String?,
    val description: String?,
    val date: String?,
    val tags: List<String>,
    val thumbnail: String?
)

// Auto-generated list of articles from markdown files
private val markdownIndex = listOf(
    ArticleDescriptor(
    route = "/blog/welcome-to-my-blog",
    filePath = "/content/blog/welcome_to_my_blog.md",
    title = "Welcome to My Blog",
    description = "An introduction to my blog and what you can expect to find here. I'll be sharing insights about software development, technology trends, and my personal journey.",
    date = "January 15, 2024",
    tags = listOf("personal", "introduction", "blog"),
    thumbnail = null
),
    ArticleDescriptor(
    route = "/portfolio/file-sorter-app",
    filePath = "/content/portfolio/file_sorter_app.md",
    title = "File Sorter",
    description = "Your ultimate solution for keeping your digital life neat and tidy! With File Sorter, you can easily organize your files on your Android device by moving them from one folder to another based on their extensions. No more cluttered folders and lost files!",
    date = "September 8, 2023",
    tags = listOf("android", "app", "hobby", "productivity"),
    thumbnail = "file-sorter-logo.webp"
)
)

fun ArticleDescriptor.toArticle(): Article {
    val slug = route.substringAfterLast("/")

    return Article(
        id = slug,
        slug = slug,
        title = title ?: "Untitled",
        content = "", // Content will be loaded separately when needed
        description = description ?: "",
        author = "Shevapro",
        dateAdded = date ?: "",
        tags = tags,
        imageUrl = if (thumbnail != null) "/assets/images/$thumbnail" else "/favicon.ico",
    )
}

/**
 * Returns a list of articles from a specific category.
 *
 * @param category The category to filter articles by (e.g., "blog", "portfolio", "design")
 * @return List of Article objects from the specified category
 */
fun getArticles(category: String): List<Article> {
    return markdownIndex
        .filter { it.route.startsWith("/$category") }
        .map { it.toArticle() }
}